# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/essential/mata/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/essential/mata/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/essential/mata/proprietary/bin/fastboot:system/bin/fastboot \
    vendor/essential/mata/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    vendor/essential/mata/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    vendor/essential/mata/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/essential/mata/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    vendor/essential/mata/proprietary/etc/firmware/TFA9891.cnt:system/etc/firmware/TFA9891.cnt \
    vendor/essential/mata/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/essential/mata/proprietary/etc/nqnfcee_access.xml:system/etc/nqnfcee_access.xml \
    vendor/essential/mata/proprietary/etc/nqnfcse_access.xml:system/etc/nqnfcse_access.xml \
    vendor/essential/mata/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.gsma.services.nfc.xml:system/etc/permissions/com.gsma.services.nfc.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.nxp.nfc.nq.xml:system/etc/permissions/com.nxp.nfc.nq.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.qti.snapdragon.sdk.display.xml:system/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/essential/mata/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/essential/mata/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/essential/mata/proprietary/etc/permissions/embms.xml:system/etc/permissions/embms.xml \
    vendor/essential/mata/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/essential/mata/proprietary/etc/permissions/privapp-permissions-mata.xml:system/etc/permissions/privapp-permissions-mata.xml \
    vendor/essential/mata/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/essential/mata/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/essential/mata/proprietary/etc/permissions/radioconfig.xml:system/etc/permissions/radioconfig.xml \
    vendor/essential/mata/proprietary/etc/permissions/radioconfiginterface.xml:system/etc/permissions/radioconfiginterface.xml \
    vendor/essential/mata/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/essential/mata/proprietary/etc/permissions/vendor-essential-hardware-sidecar.xml:system/etc/permissions/vendor-essential-hardware-sidecar.xml \
    vendor/essential/mata/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/essential/mata/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/essential/mata/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/essential/mata/proprietary/lib/lib-imscamera.so:system/lib/lib-imscamera.so \
    vendor/essential/mata/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/essential/mata/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/essential/mata/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/essential/mata/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/essential/mata/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/essential/mata/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/essential/mata/proprietary/lib/libdpmnsrm.so:system/lib/libdpmnsrm.so \
    vendor/essential/mata/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/essential/mata/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/essential/mata/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/essential/mata/proprietary/lib/liblocationservice_jni.so:system/lib/liblocationservice_jni.so \
    vendor/essential/mata/proprietary/lib/libtsext_inf.so:system/lib/libtsext_inf.so \
    vendor/essential/mata/proprietary/lib/sensors.hal.tof.so:system/lib/sensors.hal.tof.so \
    vendor/essential/mata/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.display.postproc@1.0.so:system/lib/vendor.display.postproc@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.essential.hardware.sidecar@1.0.so:system/lib/vendor.essential.hardware.sidecar@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.improvetouch.blobmanager@1.0.so:system/lib/vendor.qti.hardware.improvetouch.blobmanager@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.improvetouch.gesturemanager@1.0.so:system/lib/vendor.qti.hardware.improvetouch.gesturemanager@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.improvetouch.touchcompanion@1.0.so:system/lib/vendor.qti.hardware.improvetouch.touchcompanion@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.qteeconnector@1.0.so:system/lib/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/essential/mata/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/essential/mata/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/essential/mata/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/essential/mata/proprietary/lib64/lib-imscamera.so:system/lib64/lib-imscamera.so \
    vendor/essential/mata/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/essential/mata/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/essential/mata/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/essential/mata/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/essential/mata/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/essential/mata/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/essential/mata/proprietary/lib64/libdpmnsrm.so:system/lib64/libdpmnsrm.so \
    vendor/essential/mata/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/essential/mata/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/essential/mata/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/essential/mata/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/essential/mata/proprietary/lib64/libnqnfc-nci.so:system/lib64/libnqnfc-nci.so \
    vendor/essential/mata/proprietary/lib64/libnqnfc_nci_jni.so:system/lib64/libnqnfc_nci_jni.so \
    vendor/essential/mata/proprietary/lib64/libp61-jcop-kit.so:system/lib64/libp61-jcop-kit.so \
    vendor/essential/mata/proprietary/lib64/libtsext_inf.so:system/lib64/libtsext_inf.so \
    vendor/essential/mata/proprietary/lib64/sensors.hal.tof.so:system/lib64/sensors.hal.tof.so \
    vendor/essential/mata/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.display.postproc@1.0.so:system/lib64/vendor.display.postproc@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.essential.hardware.sidecar@1.0.so:system/lib64/vendor.essential.hardware.sidecar@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.nxp.hardware.nfc@1.0.so:system/lib64/vendor.nxp.hardware.nfc@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.improvetouch.blobmanager@1.0.so:system/lib64/vendor.qti.hardware.improvetouch.blobmanager@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.improvetouch.gesturemanager@1.0.so:system/lib64/vendor.qti.hardware.improvetouch.gesturemanager@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.improvetouch.touchcompanion@1.0.so:system/lib64/vendor.qti.hardware.improvetouch.touchcompanion@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.iop@1.0.so:system/lib64/vendor.qti.hardware.iop@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/lib64/vendor.qti.hardware.perf@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.qteeconnector@1.0.so:system/lib64/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so \
    vendor/essential/mata/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    NQNfcNci \
    QtiTelephonyService \
    Score \
    datastatusnotification \
    embms \
    ims \
    radioconfig \
    CNEService \
    HotwordEnrollmentOKGoogleWCD9335 \
    HotwordEnrollmentTGoogleWCD9335 \
    HotwordEnrollmentXGoogleWCD9335 \
    Klik \
    com.qualcomm.location \
    dpmserviceapp \
    qcrilmsgtunnel \
    QtiTelephonyServicelibrary \
    cneapiclient \
    com.gsma.services.nfc \
    com.nxp.nfc.nq \
    com.qti.dpmframework \
    com.qti.location.sdk \
    com.qti.snapdragon.sdk.display \
    com.quicinc.cne.api-V1.0-java \
    com.quicinc.cne \
    dpmapi \
    embmslibrary \
    izat.xt.srv \
    qcrilhook \
    qti-telephony-common \
    tcmclient \
    vendor.qti.hardware.fingerprint-V1.0-java
